package com.internet.cms.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.internet.cms.model.Point;
import com.internet.cms.model.PointExample;

public interface PointService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int countByExample(PointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int deleteByExample(PointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int deleteByPrimaryKey(Integer pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int insert(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int insertSelective(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    List<Point> selectByExample(PointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    Point selectByPrimaryKey(Integer pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") Point record, @Param("example") PointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int updateByExample(@Param("record") Point record, @Param("example") PointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int updateByPrimaryKeySelective(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Sun Apr 09 17:19:45 CST 2017
     */
    int updateByPrimaryKey(Point record);
}
