package com.internet.cms.dao;

import com.internet.cms.model.ChoiceQuestion;
import com.internet.cms.model.ChoiceQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChoiceQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int countByExample(ChoiceQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int deleteByExample(ChoiceQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int insert(ChoiceQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int insertSelective(ChoiceQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    List<ChoiceQuestion> selectByExample(ChoiceQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    ChoiceQuestion selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") ChoiceQuestion record, @Param("example") ChoiceQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int updateByExample(@Param("record") ChoiceQuestion record, @Param("example") ChoiceQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int updateByPrimaryKeySelective(ChoiceQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_question
     *
     * @mbggenerated Sun Apr 09 17:14:00 CST 2017
     */
    int updateByPrimaryKey(ChoiceQuestion record);
}