package com.internet.cms.dao;

import com.internet.cms.model.EssayQuestion;
import com.internet.cms.model.EssayQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EssayQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int countByExample(EssayQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int deleteByExample(EssayQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int insert(EssayQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int insertSelective(EssayQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    List<EssayQuestion> selectByExample(EssayQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    EssayQuestion selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") EssayQuestion record, @Param("example") EssayQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int updateByExample(@Param("record") EssayQuestion record, @Param("example") EssayQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int updateByPrimaryKeySelective(EssayQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay_question
     *
     * @mbggenerated Sun Apr 09 17:18:49 CST 2017
     */
    int updateByPrimaryKey(EssayQuestion record);
}