package com.internet.cms.model;

import java.util.ArrayList;
import java.util.List;

public class ChoiceErrorExample extends PageInfo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public ChoiceErrorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Integer value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Integer value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Integer value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Integer value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Integer> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Integer> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionNameIsNull() {
            addCriterion("question_name is null");
            return (Criteria) this;
        }

        public Criteria andQuestionNameIsNotNull() {
            addCriterion("question_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionNameEqualTo(String value) {
            addCriterion("question_name =", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotEqualTo(String value) {
            addCriterion("question_name <>", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameGreaterThan(String value) {
            addCriterion("question_name >", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameGreaterThanOrEqualTo(String value) {
            addCriterion("question_name >=", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameLessThan(String value) {
            addCriterion("question_name <", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameLessThanOrEqualTo(String value) {
            addCriterion("question_name <=", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameLike(String value) {
            addCriterion("question_name like", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotLike(String value) {
            addCriterion("question_name not like", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameIn(List<String> values) {
            addCriterion("question_name in", values, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotIn(List<String> values) {
            addCriterion("question_name not in", values, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameBetween(String value1, String value2) {
            addCriterion("question_name between", value1, value2, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotBetween(String value1, String value2) {
            addCriterion("question_name not between", value1, value2, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeIsNull() {
            addCriterion("question_type is null");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeIsNotNull() {
            addCriterion("question_type is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeEqualTo(Integer value) {
            addCriterion("question_type =", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeNotEqualTo(Integer value) {
            addCriterion("question_type <>", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeGreaterThan(Integer value) {
            addCriterion("question_type >", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_type >=", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeLessThan(Integer value) {
            addCriterion("question_type <", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeLessThanOrEqualTo(Integer value) {
            addCriterion("question_type <=", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeIn(List<Integer> values) {
            addCriterion("question_type in", values, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeNotIn(List<Integer> values) {
            addCriterion("question_type not in", values, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeBetween(Integer value1, Integer value2) {
            addCriterion("question_type between", value1, value2, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("question_type not between", value1, value2, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionStateIsNull() {
            addCriterion("question_state is null");
            return (Criteria) this;
        }

        public Criteria andQuestionStateIsNotNull() {
            addCriterion("question_state is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionStateEqualTo(Integer value) {
            addCriterion("question_state =", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateNotEqualTo(Integer value) {
            addCriterion("question_state <>", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateGreaterThan(Integer value) {
            addCriterion("question_state >", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_state >=", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateLessThan(Integer value) {
            addCriterion("question_state <", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateLessThanOrEqualTo(Integer value) {
            addCriterion("question_state <=", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateIn(List<Integer> values) {
            addCriterion("question_state in", values, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateNotIn(List<Integer> values) {
            addCriterion("question_state not in", values, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateBetween(Integer value1, Integer value2) {
            addCriterion("question_state between", value1, value2, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateNotBetween(Integer value1, Integer value2) {
            addCriterion("question_state not between", value1, value2, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionAIsNull() {
            addCriterion("question_option_a is null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionAIsNotNull() {
            addCriterion("question_option_a is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionAEqualTo(String value) {
            addCriterion("question_option_a =", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionANotEqualTo(String value) {
            addCriterion("question_option_a <>", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionAGreaterThan(String value) {
            addCriterion("question_option_a >", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionAGreaterThanOrEqualTo(String value) {
            addCriterion("question_option_a >=", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionALessThan(String value) {
            addCriterion("question_option_a <", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionALessThanOrEqualTo(String value) {
            addCriterion("question_option_a <=", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionALike(String value) {
            addCriterion("question_option_a like", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionANotLike(String value) {
            addCriterion("question_option_a not like", value, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionAIn(List<String> values) {
            addCriterion("question_option_a in", values, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionANotIn(List<String> values) {
            addCriterion("question_option_a not in", values, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionABetween(String value1, String value2) {
            addCriterion("question_option_a between", value1, value2, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionANotBetween(String value1, String value2) {
            addCriterion("question_option_a not between", value1, value2, "questionOptionA");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBIsNull() {
            addCriterion("question_option_b is null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBIsNotNull() {
            addCriterion("question_option_b is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBEqualTo(String value) {
            addCriterion("question_option_b =", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBNotEqualTo(String value) {
            addCriterion("question_option_b <>", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBGreaterThan(String value) {
            addCriterion("question_option_b >", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBGreaterThanOrEqualTo(String value) {
            addCriterion("question_option_b >=", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBLessThan(String value) {
            addCriterion("question_option_b <", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBLessThanOrEqualTo(String value) {
            addCriterion("question_option_b <=", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBLike(String value) {
            addCriterion("question_option_b like", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBNotLike(String value) {
            addCriterion("question_option_b not like", value, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBIn(List<String> values) {
            addCriterion("question_option_b in", values, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBNotIn(List<String> values) {
            addCriterion("question_option_b not in", values, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBBetween(String value1, String value2) {
            addCriterion("question_option_b between", value1, value2, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionBNotBetween(String value1, String value2) {
            addCriterion("question_option_b not between", value1, value2, "questionOptionB");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCIsNull() {
            addCriterion("question_option_c is null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCIsNotNull() {
            addCriterion("question_option_c is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCEqualTo(String value) {
            addCriterion("question_option_c =", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCNotEqualTo(String value) {
            addCriterion("question_option_c <>", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCGreaterThan(String value) {
            addCriterion("question_option_c >", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCGreaterThanOrEqualTo(String value) {
            addCriterion("question_option_c >=", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCLessThan(String value) {
            addCriterion("question_option_c <", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCLessThanOrEqualTo(String value) {
            addCriterion("question_option_c <=", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCLike(String value) {
            addCriterion("question_option_c like", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCNotLike(String value) {
            addCriterion("question_option_c not like", value, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCIn(List<String> values) {
            addCriterion("question_option_c in", values, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCNotIn(List<String> values) {
            addCriterion("question_option_c not in", values, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCBetween(String value1, String value2) {
            addCriterion("question_option_c between", value1, value2, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionCNotBetween(String value1, String value2) {
            addCriterion("question_option_c not between", value1, value2, "questionOptionC");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDIsNull() {
            addCriterion("question_option_d is null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDIsNotNull() {
            addCriterion("question_option_d is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDEqualTo(String value) {
            addCriterion("question_option_d =", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDNotEqualTo(String value) {
            addCriterion("question_option_d <>", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDGreaterThan(String value) {
            addCriterion("question_option_d >", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDGreaterThanOrEqualTo(String value) {
            addCriterion("question_option_d >=", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDLessThan(String value) {
            addCriterion("question_option_d <", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDLessThanOrEqualTo(String value) {
            addCriterion("question_option_d <=", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDLike(String value) {
            addCriterion("question_option_d like", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDNotLike(String value) {
            addCriterion("question_option_d not like", value, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDIn(List<String> values) {
            addCriterion("question_option_d in", values, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDNotIn(List<String> values) {
            addCriterion("question_option_d not in", values, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDBetween(String value1, String value2) {
            addCriterion("question_option_d between", value1, value2, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionDNotBetween(String value1, String value2) {
            addCriterion("question_option_d not between", value1, value2, "questionOptionD");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionIsNull() {
            addCriterion("correct_option is null");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionIsNotNull() {
            addCriterion("correct_option is not null");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionEqualTo(String value) {
            addCriterion("correct_option =", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionNotEqualTo(String value) {
            addCriterion("correct_option <>", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionGreaterThan(String value) {
            addCriterion("correct_option >", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionGreaterThanOrEqualTo(String value) {
            addCriterion("correct_option >=", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionLessThan(String value) {
            addCriterion("correct_option <", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionLessThanOrEqualTo(String value) {
            addCriterion("correct_option <=", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionLike(String value) {
            addCriterion("correct_option like", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionNotLike(String value) {
            addCriterion("correct_option not like", value, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionIn(List<String> values) {
            addCriterion("correct_option in", values, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionNotIn(List<String> values) {
            addCriterion("correct_option not in", values, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionBetween(String value1, String value2) {
            addCriterion("correct_option between", value1, value2, "correctOption");
            return (Criteria) this;
        }

        public Criteria andCorrectOptionNotBetween(String value1, String value2) {
            addCriterion("correct_option not between", value1, value2, "correctOption");
            return (Criteria) this;
        }

        public Criteria andPointIdIsNull() {
            addCriterion("point_id is null");
            return (Criteria) this;
        }

        public Criteria andPointIdIsNotNull() {
            addCriterion("point_id is not null");
            return (Criteria) this;
        }

        public Criteria andPointIdEqualTo(Integer value) {
            addCriterion("point_id =", value, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdNotEqualTo(Integer value) {
            addCriterion("point_id <>", value, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdGreaterThan(Integer value) {
            addCriterion("point_id >", value, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("point_id >=", value, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdLessThan(Integer value) {
            addCriterion("point_id <", value, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdLessThanOrEqualTo(Integer value) {
            addCriterion("point_id <=", value, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdIn(List<Integer> values) {
            addCriterion("point_id in", values, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdNotIn(List<Integer> values) {
            addCriterion("point_id not in", values, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdBetween(Integer value1, Integer value2) {
            addCriterion("point_id between", value1, value2, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointIdNotBetween(Integer value1, Integer value2) {
            addCriterion("point_id not between", value1, value2, "pointId");
            return (Criteria) this;
        }

        public Criteria andPointNameIsNull() {
            addCriterion("point_name is null");
            return (Criteria) this;
        }

        public Criteria andPointNameIsNotNull() {
            addCriterion("point_name is not null");
            return (Criteria) this;
        }

        public Criteria andPointNameEqualTo(String value) {
            addCriterion("point_name =", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameNotEqualTo(String value) {
            addCriterion("point_name <>", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameGreaterThan(String value) {
            addCriterion("point_name >", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameGreaterThanOrEqualTo(String value) {
            addCriterion("point_name >=", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameLessThan(String value) {
            addCriterion("point_name <", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameLessThanOrEqualTo(String value) {
            addCriterion("point_name <=", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameLike(String value) {
            addCriterion("point_name like", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameNotLike(String value) {
            addCriterion("point_name not like", value, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameIn(List<String> values) {
            addCriterion("point_name in", values, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameNotIn(List<String> values) {
            addCriterion("point_name not in", values, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameBetween(String value1, String value2) {
            addCriterion("point_name between", value1, value2, "pointName");
            return (Criteria) this;
        }

        public Criteria andPointNameNotBetween(String value1, String value2) {
            addCriterion("point_name not between", value1, value2, "pointName");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Integer value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Integer value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Integer value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Integer value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Integer> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Integer> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Integer value1, Integer value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNull() {
            addCriterion("subject_name is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNotNull() {
            addCriterion("subject_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameEqualTo(String value) {
            addCriterion("subject_name =", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotEqualTo(String value) {
            addCriterion("subject_name <>", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThan(String value) {
            addCriterion("subject_name >", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("subject_name >=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThan(String value) {
            addCriterion("subject_name <", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThanOrEqualTo(String value) {
            addCriterion("subject_name <=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLike(String value) {
            addCriterion("subject_name like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotLike(String value) {
            addCriterion("subject_name not like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIn(List<String> values) {
            addCriterion("subject_name in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotIn(List<String> values) {
            addCriterion("subject_name not in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameBetween(String value1, String value2) {
            addCriterion("subject_name between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotBetween(String value1, String value2) {
            addCriterion("subject_name not between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table choice_error
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 26 12:47:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table choice_error
     *
     * @mbggenerated Wed Apr 26 12:47:31 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}