package com.internet.cms.model;

public class Classes extends PageInfo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_id
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_name
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_date
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    private String classDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_major
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    private String classMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_state
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    private Integer classState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_id
     *
     * @return the value of class.class_id
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_id
     *
     * @param classId the value for class.class_id
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_name
     *
     * @return the value of class.class_name
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_name
     *
     * @param className the value for class.class_name
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_date
     *
     * @return the value of class.class_date
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public String getClassDate() {
        return classDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_date
     *
     * @param classDate the value for class.class_date
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public void setClassDate(String classDate) {
        this.classDate = classDate == null ? null : classDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_major
     *
     * @return the value of class.class_major
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public String getClassMajor() {
        return classMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_major
     *
     * @param classMajor the value for class.class_major
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public void setClassMajor(String classMajor) {
        this.classMajor = classMajor == null ? null : classMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_state
     *
     * @return the value of class.class_state
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public Integer getClassState() {
        return classState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_state
     *
     * @param classState the value for class.class_state
     *
     * @mbggenerated Wed Apr 19 13:08:30 CST 2017
     */
    public void setClassState(Integer classState) {
        this.classState = classState;
    }
}