package com.internet.cms.model;

public class EssayQuestion extends PageInfo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.question_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.question_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private String questionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.question_state
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private Integer questionState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.question_answer
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private String questionAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.point_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private Integer pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.point_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.subject_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay_question.subject_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    private String subjectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.question_id
     *
     * @return the value of essay_question.question_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.question_id
     *
     * @param questionId the value for essay_question.question_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.question_name
     *
     * @return the value of essay_question.question_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public String getQuestionName() {
        return questionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.question_name
     *
     * @param questionName the value for essay_question.question_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setQuestionName(String questionName) {
        this.questionName = questionName == null ? null : questionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.question_state
     *
     * @return the value of essay_question.question_state
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public Integer getQuestionState() {
        return questionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.question_state
     *
     * @param questionState the value for essay_question.question_state
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setQuestionState(Integer questionState) {
        this.questionState = questionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.question_answer
     *
     * @return the value of essay_question.question_answer
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public String getQuestionAnswer() {
        return questionAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.question_answer
     *
     * @param questionAnswer the value for essay_question.question_answer
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setQuestionAnswer(String questionAnswer) {
        this.questionAnswer = questionAnswer == null ? null : questionAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.point_id
     *
     * @return the value of essay_question.point_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public Integer getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.point_id
     *
     * @param pointId the value for essay_question.point_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setPointId(Integer pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.point_name
     *
     * @return the value of essay_question.point_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.point_name
     *
     * @param pointName the value for essay_question.point_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.subject_id
     *
     * @return the value of essay_question.subject_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.subject_id
     *
     * @param subjectId the value for essay_question.subject_id
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay_question.subject_name
     *
     * @return the value of essay_question.subject_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay_question.subject_name
     *
     * @param subjectName the value for essay_question.subject_name
     *
     * @mbggenerated Wed Apr 19 22:59:53 CST 2017
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }
}