package com.internet.cms.model;

import java.util.Date;

public class Exam extends PageInfo{
	
	//学生的考试状态：0.没有到可以考试的时间  1.可以考然后未考 2.可以考已经考了 3.时间过了
	private int state;
	
	public int getState() {
		return state;
	}
	public void setState(int state) {
		this.state = state;
	}
	
	//显示出自己科目的所有考试，标记是否是自己发布的（自己的可以编辑）0.可以编辑  1.不可以编辑
	private int edit;
	
	public int getEdit() {
		return edit;
	}
	public void setEdit(int edit) {
		this.edit = edit;
	}

	private String examDateTemp;
    public String getExamDateTemp() {
		return examDateTemp;
	}
	public void setExamDateTemp(String examDateTemp) {
		this.examDateTemp = examDateTemp;
	}
	private String start;
	private String end;
	
	
	public String getStart() {
		return start;
	}
	public void setStart(String start) {
		this.start = start;
	}
	public String getEnd() {
		return end;
	}
	public void setEnd(String end) {
		this.end = end;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_no
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private String examNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private String examName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.radio_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer radioNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.radio_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer radioScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.check_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer checkNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.check_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer checkScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.judge_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer judgeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.judge_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer judgeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.essay_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer essayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.essay_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer essayScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.class_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.class_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_date
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Date examDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.start_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.end_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer examTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_state
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer examState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.room_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.room_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.subject_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.subject_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.user_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.user_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_id
     *
     * @return the value of exam.exam_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_id
     *
     * @param examId the value for exam.exam_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_no
     *
     * @return the value of exam.exam_no
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public String getExamNo() {
        return examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_no
     *
     * @param examNo the value for exam.exam_no
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setExamNo(String examNo) {
        this.examNo = examNo == null ? null : examNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_name
     *
     * @return the value of exam.exam_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_name
     *
     * @param examName the value for exam.exam_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.radio_num
     *
     * @return the value of exam.radio_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getRadioNum() {
        return radioNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.radio_num
     *
     * @param radioNum the value for exam.radio_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setRadioNum(Integer radioNum) {
        this.radioNum = radioNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.radio_score
     *
     * @return the value of exam.radio_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getRadioScore() {
        return radioScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.radio_score
     *
     * @param radioScore the value for exam.radio_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setRadioScore(Integer radioScore) {
        this.radioScore = radioScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.check_num
     *
     * @return the value of exam.check_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getCheckNum() {
        return checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.check_num
     *
     * @param checkNum the value for exam.check_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setCheckNum(Integer checkNum) {
        this.checkNum = checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.check_score
     *
     * @return the value of exam.check_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getCheckScore() {
        return checkScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.check_score
     *
     * @param checkScore the value for exam.check_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setCheckScore(Integer checkScore) {
        this.checkScore = checkScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.judge_num
     *
     * @return the value of exam.judge_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getJudgeNum() {
        return judgeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.judge_num
     *
     * @param judgeNum the value for exam.judge_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setJudgeNum(Integer judgeNum) {
        this.judgeNum = judgeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.judge_score
     *
     * @return the value of exam.judge_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getJudgeScore() {
        return judgeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.judge_score
     *
     * @param judgeScore the value for exam.judge_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setJudgeScore(Integer judgeScore) {
        this.judgeScore = judgeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.essay_num
     *
     * @return the value of exam.essay_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getEssayNum() {
        return essayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.essay_num
     *
     * @param essayNum the value for exam.essay_num
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setEssayNum(Integer essayNum) {
        this.essayNum = essayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.essay_score
     *
     * @return the value of exam.essay_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getEssayScore() {
        return essayScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.essay_score
     *
     * @param essayScore the value for exam.essay_score
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setEssayScore(Integer essayScore) {
        this.essayScore = essayScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.class_id
     *
     * @return the value of exam.class_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.class_id
     *
     * @param classId the value for exam.class_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.class_name
     *
     * @return the value of exam.class_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.class_name
     *
     * @param className the value for exam.class_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_date
     *
     * @return the value of exam.exam_date
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Date getExamDate() {
        return examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_date
     *
     * @param examDate the value for exam.exam_date
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.start_time
     *
     * @return the value of exam.start_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.start_time
     *
     * @param startTime the value for exam.start_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.end_time
     *
     * @return the value of exam.end_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.end_time
     *
     * @param endTime the value for exam.end_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_time
     *
     * @return the value of exam.exam_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_time
     *
     * @param examTime the value for exam.exam_time
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setExamTime(Integer examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_state
     *
     * @return the value of exam.exam_state
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getExamState() {
        return examState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_state
     *
     * @param examState the value for exam.exam_state
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setExamState(Integer examState) {
        this.examState = examState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.room_id
     *
     * @return the value of exam.room_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.room_id
     *
     * @param roomId the value for exam.room_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.room_name
     *
     * @return the value of exam.room_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.room_name
     *
     * @param roomName the value for exam.room_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.subject_id
     *
     * @return the value of exam.subject_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.subject_id
     *
     * @param subjectId the value for exam.subject_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.subject_name
     *
     * @return the value of exam.subject_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.subject_name
     *
     * @param subjectName the value for exam.subject_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.user_id
     *
     * @return the value of exam.user_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.user_id
     *
     * @param userId the value for exam.user_id
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.user_name
     *
     * @return the value of exam.user_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.user_name
     *
     * @param userName the value for exam.user_name
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}