package com.internet.cms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ExamExample extends PageInfo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public ExamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andExamIdIsNull() {
            addCriterion("exam_id is null");
            return (Criteria) this;
        }

        public Criteria andExamIdIsNotNull() {
            addCriterion("exam_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamIdEqualTo(Integer value) {
            addCriterion("exam_id =", value, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdNotEqualTo(Integer value) {
            addCriterion("exam_id <>", value, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdGreaterThan(Integer value) {
            addCriterion("exam_id >", value, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_id >=", value, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdLessThan(Integer value) {
            addCriterion("exam_id <", value, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_id <=", value, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdIn(List<Integer> values) {
            addCriterion("exam_id in", values, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdNotIn(List<Integer> values) {
            addCriterion("exam_id not in", values, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_id between", value1, value2, "examId");
            return (Criteria) this;
        }

        public Criteria andExamIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_id not between", value1, value2, "examId");
            return (Criteria) this;
        }

        public Criteria andExamNoIsNull() {
            addCriterion("exam_no is null");
            return (Criteria) this;
        }

        public Criteria andExamNoIsNotNull() {
            addCriterion("exam_no is not null");
            return (Criteria) this;
        }

        public Criteria andExamNoEqualTo(String value) {
            addCriterion("exam_no =", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoNotEqualTo(String value) {
            addCriterion("exam_no <>", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoGreaterThan(String value) {
            addCriterion("exam_no >", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoGreaterThanOrEqualTo(String value) {
            addCriterion("exam_no >=", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoLessThan(String value) {
            addCriterion("exam_no <", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoLessThanOrEqualTo(String value) {
            addCriterion("exam_no <=", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoLike(String value) {
            addCriterion("exam_no like", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoNotLike(String value) {
            addCriterion("exam_no not like", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoIn(List<String> values) {
            addCriterion("exam_no in", values, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoNotIn(List<String> values) {
            addCriterion("exam_no not in", values, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoBetween(String value1, String value2) {
            addCriterion("exam_no between", value1, value2, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoNotBetween(String value1, String value2) {
            addCriterion("exam_no not between", value1, value2, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNameIsNull() {
            addCriterion("exam_name is null");
            return (Criteria) this;
        }

        public Criteria andExamNameIsNotNull() {
            addCriterion("exam_name is not null");
            return (Criteria) this;
        }

        public Criteria andExamNameEqualTo(String value) {
            addCriterion("exam_name =", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameNotEqualTo(String value) {
            addCriterion("exam_name <>", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameGreaterThan(String value) {
            addCriterion("exam_name >", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameGreaterThanOrEqualTo(String value) {
            addCriterion("exam_name >=", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameLessThan(String value) {
            addCriterion("exam_name <", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameLessThanOrEqualTo(String value) {
            addCriterion("exam_name <=", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameLike(String value) {
            addCriterion("exam_name like", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameNotLike(String value) {
            addCriterion("exam_name not like", value, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameIn(List<String> values) {
            addCriterion("exam_name in", values, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameNotIn(List<String> values) {
            addCriterion("exam_name not in", values, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameBetween(String value1, String value2) {
            addCriterion("exam_name between", value1, value2, "examName");
            return (Criteria) this;
        }

        public Criteria andExamNameNotBetween(String value1, String value2) {
            addCriterion("exam_name not between", value1, value2, "examName");
            return (Criteria) this;
        }

        public Criteria andRadioNumIsNull() {
            addCriterion("radio_num is null");
            return (Criteria) this;
        }

        public Criteria andRadioNumIsNotNull() {
            addCriterion("radio_num is not null");
            return (Criteria) this;
        }

        public Criteria andRadioNumEqualTo(Integer value) {
            addCriterion("radio_num =", value, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumNotEqualTo(Integer value) {
            addCriterion("radio_num <>", value, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumGreaterThan(Integer value) {
            addCriterion("radio_num >", value, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("radio_num >=", value, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumLessThan(Integer value) {
            addCriterion("radio_num <", value, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumLessThanOrEqualTo(Integer value) {
            addCriterion("radio_num <=", value, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumIn(List<Integer> values) {
            addCriterion("radio_num in", values, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumNotIn(List<Integer> values) {
            addCriterion("radio_num not in", values, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumBetween(Integer value1, Integer value2) {
            addCriterion("radio_num between", value1, value2, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioNumNotBetween(Integer value1, Integer value2) {
            addCriterion("radio_num not between", value1, value2, "radioNum");
            return (Criteria) this;
        }

        public Criteria andRadioScoreIsNull() {
            addCriterion("radio_score is null");
            return (Criteria) this;
        }

        public Criteria andRadioScoreIsNotNull() {
            addCriterion("radio_score is not null");
            return (Criteria) this;
        }

        public Criteria andRadioScoreEqualTo(Integer value) {
            addCriterion("radio_score =", value, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreNotEqualTo(Integer value) {
            addCriterion("radio_score <>", value, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreGreaterThan(Integer value) {
            addCriterion("radio_score >", value, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("radio_score >=", value, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreLessThan(Integer value) {
            addCriterion("radio_score <", value, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreLessThanOrEqualTo(Integer value) {
            addCriterion("radio_score <=", value, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreIn(List<Integer> values) {
            addCriterion("radio_score in", values, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreNotIn(List<Integer> values) {
            addCriterion("radio_score not in", values, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreBetween(Integer value1, Integer value2) {
            addCriterion("radio_score between", value1, value2, "radioScore");
            return (Criteria) this;
        }

        public Criteria andRadioScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("radio_score not between", value1, value2, "radioScore");
            return (Criteria) this;
        }

        public Criteria andCheckNumIsNull() {
            addCriterion("check_num is null");
            return (Criteria) this;
        }

        public Criteria andCheckNumIsNotNull() {
            addCriterion("check_num is not null");
            return (Criteria) this;
        }

        public Criteria andCheckNumEqualTo(Integer value) {
            addCriterion("check_num =", value, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumNotEqualTo(Integer value) {
            addCriterion("check_num <>", value, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumGreaterThan(Integer value) {
            addCriterion("check_num >", value, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_num >=", value, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumLessThan(Integer value) {
            addCriterion("check_num <", value, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumLessThanOrEqualTo(Integer value) {
            addCriterion("check_num <=", value, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumIn(List<Integer> values) {
            addCriterion("check_num in", values, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumNotIn(List<Integer> values) {
            addCriterion("check_num not in", values, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumBetween(Integer value1, Integer value2) {
            addCriterion("check_num between", value1, value2, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckNumNotBetween(Integer value1, Integer value2) {
            addCriterion("check_num not between", value1, value2, "checkNum");
            return (Criteria) this;
        }

        public Criteria andCheckScoreIsNull() {
            addCriterion("check_score is null");
            return (Criteria) this;
        }

        public Criteria andCheckScoreIsNotNull() {
            addCriterion("check_score is not null");
            return (Criteria) this;
        }

        public Criteria andCheckScoreEqualTo(Integer value) {
            addCriterion("check_score =", value, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreNotEqualTo(Integer value) {
            addCriterion("check_score <>", value, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreGreaterThan(Integer value) {
            addCriterion("check_score >", value, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_score >=", value, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreLessThan(Integer value) {
            addCriterion("check_score <", value, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreLessThanOrEqualTo(Integer value) {
            addCriterion("check_score <=", value, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreIn(List<Integer> values) {
            addCriterion("check_score in", values, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreNotIn(List<Integer> values) {
            addCriterion("check_score not in", values, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreBetween(Integer value1, Integer value2) {
            addCriterion("check_score between", value1, value2, "checkScore");
            return (Criteria) this;
        }

        public Criteria andCheckScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("check_score not between", value1, value2, "checkScore");
            return (Criteria) this;
        }

        public Criteria andJudgeNumIsNull() {
            addCriterion("judge_num is null");
            return (Criteria) this;
        }

        public Criteria andJudgeNumIsNotNull() {
            addCriterion("judge_num is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeNumEqualTo(Integer value) {
            addCriterion("judge_num =", value, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumNotEqualTo(Integer value) {
            addCriterion("judge_num <>", value, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumGreaterThan(Integer value) {
            addCriterion("judge_num >", value, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("judge_num >=", value, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumLessThan(Integer value) {
            addCriterion("judge_num <", value, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumLessThanOrEqualTo(Integer value) {
            addCriterion("judge_num <=", value, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumIn(List<Integer> values) {
            addCriterion("judge_num in", values, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumNotIn(List<Integer> values) {
            addCriterion("judge_num not in", values, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumBetween(Integer value1, Integer value2) {
            addCriterion("judge_num between", value1, value2, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeNumNotBetween(Integer value1, Integer value2) {
            addCriterion("judge_num not between", value1, value2, "judgeNum");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreIsNull() {
            addCriterion("judge_score is null");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreIsNotNull() {
            addCriterion("judge_score is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreEqualTo(Integer value) {
            addCriterion("judge_score =", value, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreNotEqualTo(Integer value) {
            addCriterion("judge_score <>", value, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreGreaterThan(Integer value) {
            addCriterion("judge_score >", value, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("judge_score >=", value, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreLessThan(Integer value) {
            addCriterion("judge_score <", value, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreLessThanOrEqualTo(Integer value) {
            addCriterion("judge_score <=", value, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreIn(List<Integer> values) {
            addCriterion("judge_score in", values, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreNotIn(List<Integer> values) {
            addCriterion("judge_score not in", values, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreBetween(Integer value1, Integer value2) {
            addCriterion("judge_score between", value1, value2, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andJudgeScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("judge_score not between", value1, value2, "judgeScore");
            return (Criteria) this;
        }

        public Criteria andEssayNumIsNull() {
            addCriterion("essay_num is null");
            return (Criteria) this;
        }

        public Criteria andEssayNumIsNotNull() {
            addCriterion("essay_num is not null");
            return (Criteria) this;
        }

        public Criteria andEssayNumEqualTo(Integer value) {
            addCriterion("essay_num =", value, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumNotEqualTo(Integer value) {
            addCriterion("essay_num <>", value, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumGreaterThan(Integer value) {
            addCriterion("essay_num >", value, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("essay_num >=", value, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumLessThan(Integer value) {
            addCriterion("essay_num <", value, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumLessThanOrEqualTo(Integer value) {
            addCriterion("essay_num <=", value, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumIn(List<Integer> values) {
            addCriterion("essay_num in", values, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumNotIn(List<Integer> values) {
            addCriterion("essay_num not in", values, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumBetween(Integer value1, Integer value2) {
            addCriterion("essay_num between", value1, value2, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayNumNotBetween(Integer value1, Integer value2) {
            addCriterion("essay_num not between", value1, value2, "essayNum");
            return (Criteria) this;
        }

        public Criteria andEssayScoreIsNull() {
            addCriterion("essay_score is null");
            return (Criteria) this;
        }

        public Criteria andEssayScoreIsNotNull() {
            addCriterion("essay_score is not null");
            return (Criteria) this;
        }

        public Criteria andEssayScoreEqualTo(Integer value) {
            addCriterion("essay_score =", value, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreNotEqualTo(Integer value) {
            addCriterion("essay_score <>", value, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreGreaterThan(Integer value) {
            addCriterion("essay_score >", value, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("essay_score >=", value, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreLessThan(Integer value) {
            addCriterion("essay_score <", value, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreLessThanOrEqualTo(Integer value) {
            addCriterion("essay_score <=", value, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreIn(List<Integer> values) {
            addCriterion("essay_score in", values, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreNotIn(List<Integer> values) {
            addCriterion("essay_score not in", values, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreBetween(Integer value1, Integer value2) {
            addCriterion("essay_score between", value1, value2, "essayScore");
            return (Criteria) this;
        }

        public Criteria andEssayScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("essay_score not between", value1, value2, "essayScore");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Integer value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Integer value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Integer value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Integer value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Integer> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Integer> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Integer value1, Integer value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andExamDateIsNull() {
            addCriterion("exam_date is null");
            return (Criteria) this;
        }

        public Criteria andExamDateIsNotNull() {
            addCriterion("exam_date is not null");
            return (Criteria) this;
        }

        public Criteria andExamDateEqualTo(Date value) {
            addCriterionForJDBCDate("exam_date =", value, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("exam_date <>", value, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateGreaterThan(Date value) {
            addCriterionForJDBCDate("exam_date >", value, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("exam_date >=", value, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateLessThan(Date value) {
            addCriterionForJDBCDate("exam_date <", value, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("exam_date <=", value, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateIn(List<Date> values) {
            addCriterionForJDBCDate("exam_date in", values, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("exam_date not in", values, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("exam_date between", value1, value2, "examDate");
            return (Criteria) this;
        }

        public Criteria andExamDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("exam_date not between", value1, value2, "examDate");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterionForJDBCTime("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterionForJDBCTime("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterionForJDBCTime("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterionForJDBCTime("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterionForJDBCTime("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterionForJDBCTime("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeIsNull() {
            addCriterion("exam_time is null");
            return (Criteria) this;
        }

        public Criteria andExamTimeIsNotNull() {
            addCriterion("exam_time is not null");
            return (Criteria) this;
        }

        public Criteria andExamTimeEqualTo(Integer value) {
            addCriterion("exam_time =", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotEqualTo(Integer value) {
            addCriterion("exam_time <>", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeGreaterThan(Integer value) {
            addCriterion("exam_time >", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_time >=", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeLessThan(Integer value) {
            addCriterion("exam_time <", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeLessThanOrEqualTo(Integer value) {
            addCriterion("exam_time <=", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeIn(List<Integer> values) {
            addCriterion("exam_time in", values, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotIn(List<Integer> values) {
            addCriterion("exam_time not in", values, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeBetween(Integer value1, Integer value2) {
            addCriterion("exam_time between", value1, value2, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_time not between", value1, value2, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamStateIsNull() {
            addCriterion("exam_state is null");
            return (Criteria) this;
        }

        public Criteria andExamStateIsNotNull() {
            addCriterion("exam_state is not null");
            return (Criteria) this;
        }

        public Criteria andExamStateEqualTo(Integer value) {
            addCriterion("exam_state =", value, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateNotEqualTo(Integer value) {
            addCriterion("exam_state <>", value, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateGreaterThan(Integer value) {
            addCriterion("exam_state >", value, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_state >=", value, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateLessThan(Integer value) {
            addCriterion("exam_state <", value, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateLessThanOrEqualTo(Integer value) {
            addCriterion("exam_state <=", value, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateIn(List<Integer> values) {
            addCriterion("exam_state in", values, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateNotIn(List<Integer> values) {
            addCriterion("exam_state not in", values, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateBetween(Integer value1, Integer value2) {
            addCriterion("exam_state between", value1, value2, "examState");
            return (Criteria) this;
        }

        public Criteria andExamStateNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_state not between", value1, value2, "examState");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNull() {
            addCriterion("room_name is null");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNotNull() {
            addCriterion("room_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNameEqualTo(String value) {
            addCriterion("room_name =", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotEqualTo(String value) {
            addCriterion("room_name <>", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThan(String value) {
            addCriterion("room_name >", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("room_name >=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThan(String value) {
            addCriterion("room_name <", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThanOrEqualTo(String value) {
            addCriterion("room_name <=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLike(String value) {
            addCriterion("room_name like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotLike(String value) {
            addCriterion("room_name not like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameIn(List<String> values) {
            addCriterion("room_name in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotIn(List<String> values) {
            addCriterion("room_name not in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameBetween(String value1, String value2) {
            addCriterion("room_name between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotBetween(String value1, String value2) {
            addCriterion("room_name not between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Integer value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Integer value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Integer value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Integer value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Integer> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Integer> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Integer value1, Integer value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNull() {
            addCriterion("subject_name is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNotNull() {
            addCriterion("subject_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameEqualTo(String value) {
            addCriterion("subject_name =", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotEqualTo(String value) {
            addCriterion("subject_name <>", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThan(String value) {
            addCriterion("subject_name >", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("subject_name >=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThan(String value) {
            addCriterion("subject_name <", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThanOrEqualTo(String value) {
            addCriterion("subject_name <=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLike(String value) {
            addCriterion("subject_name like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotLike(String value) {
            addCriterion("subject_name not like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIn(List<String> values) {
            addCriterion("subject_name in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotIn(List<String> values) {
            addCriterion("subject_name not in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameBetween(String value1, String value2) {
            addCriterion("subject_name between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotBetween(String value1, String value2) {
            addCriterion("subject_name not between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 24 21:56:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam
     *
     * @mbggenerated Mon Apr 24 21:56:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}