package com.internet.cms.model;

public class JudgeQuestion extends PageInfo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_question.question_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_question.question_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    private String questionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_question.correct_answer
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    private String correctAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_question.point_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    private Integer pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_question.point_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_question.subject_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_question.subject_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    private String subjectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_question.question_id
     *
     * @return the value of judge_question.question_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_question.question_id
     *
     * @param questionId the value for judge_question.question_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_question.question_name
     *
     * @return the value of judge_question.question_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public String getQuestionName() {
        return questionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_question.question_name
     *
     * @param questionName the value for judge_question.question_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public void setQuestionName(String questionName) {
        this.questionName = questionName == null ? null : questionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_question.correct_answer
     *
     * @return the value of judge_question.correct_answer
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public String getCorrectAnswer() {
        return correctAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_question.correct_answer
     *
     * @param correctAnswer the value for judge_question.correct_answer
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer == null ? null : correctAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_question.point_id
     *
     * @return the value of judge_question.point_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public Integer getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_question.point_id
     *
     * @param pointId the value for judge_question.point_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public void setPointId(Integer pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_question.point_name
     *
     * @return the value of judge_question.point_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_question.point_name
     *
     * @param pointName the value for judge_question.point_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_question.subject_id
     *
     * @return the value of judge_question.subject_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_question.subject_id
     *
     * @param subjectId the value for judge_question.subject_id
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_question.subject_name
     *
     * @return the value of judge_question.subject_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_question.subject_name
     *
     * @param subjectName the value for judge_question.subject_name
     *
     * @mbggenerated Mon Apr 24 19:15:38 CST 2017
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }
}