package com.internet.cms.model;

public class Point extends PageInfo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_id
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    private Integer pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_name
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.subject_id
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.subject_name
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_content
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    private String pointContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_id
     *
     * @return the value of point.point_id
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public Integer getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_id
     *
     * @param pointId the value for point.point_id
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public void setPointId(Integer pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_name
     *
     * @return the value of point.point_name
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_name
     *
     * @param pointName the value for point.point_name
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.subject_id
     *
     * @return the value of point.subject_id
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.subject_id
     *
     * @param subjectId the value for point.subject_id
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.subject_name
     *
     * @return the value of point.subject_name
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.subject_name
     *
     * @param subjectName the value for point.subject_name
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_content
     *
     * @return the value of point.point_content
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public String getPointContent() {
        return pointContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_content
     *
     * @param pointContent the value for point.point_content
     *
     * @mbggenerated Wed Apr 19 22:38:48 CST 2017
     */
    public void setPointContent(String pointContent) {
        this.pointContent = pointContent == null ? null : pointContent.trim();
    }
}