package com.internet.cms.model;

import java.util.Date;

public class Score extends PageInfo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score_id
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private Integer scoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score_choice
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private Integer scoreChoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score_essay
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private Integer scoreEssay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.essay_question
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private String essayQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.essay_state
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private Integer essayState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score_sum
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private Integer scoreSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_id
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_no
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private String studentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_name
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.exam_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.exam_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    private String examName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.subject_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.subject_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.class_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.class_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.submit_time
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    private Date submitTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score_id
     *
     * @return the value of score.score_id
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public Integer getScoreId() {
        return scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score_id
     *
     * @param scoreId the value for score.score_id
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setScoreId(Integer scoreId) {
        this.scoreId = scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score_choice
     *
     * @return the value of score.score_choice
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public Integer getScoreChoice() {
        return scoreChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score_choice
     *
     * @param scoreChoice the value for score.score_choice
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setScoreChoice(Integer scoreChoice) {
        this.scoreChoice = scoreChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score_essay
     *
     * @return the value of score.score_essay
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public Integer getScoreEssay() {
        return scoreEssay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score_essay
     *
     * @param scoreEssay the value for score.score_essay
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setScoreEssay(Integer scoreEssay) {
        this.scoreEssay = scoreEssay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.essay_question
     *
     * @return the value of score.essay_question
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public String getEssayQuestion() {
        return essayQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.essay_question
     *
     * @param essayQuestion the value for score.essay_question
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setEssayQuestion(String essayQuestion) {
        this.essayQuestion = essayQuestion == null ? null : essayQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.essay_state
     *
     * @return the value of score.essay_state
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public Integer getEssayState() {
        return essayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.essay_state
     *
     * @param essayState the value for score.essay_state
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setEssayState(Integer essayState) {
        this.essayState = essayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score_sum
     *
     * @return the value of score.score_sum
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public Integer getScoreSum() {
        return scoreSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score_sum
     *
     * @param scoreSum the value for score.score_sum
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setScoreSum(Integer scoreSum) {
        this.scoreSum = scoreSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_id
     *
     * @return the value of score.student_id
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_id
     *
     * @param studentId the value for score.student_id
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_no
     *
     * @return the value of score.student_no
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_no
     *
     * @param studentNo the value for score.student_no
     *
     * @mbggenerated Fri Apr 28 04:47:30 CST 2017
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_name
     *
     * @return the value of score.student_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_name
     *
     * @param studentName the value for score.student_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.exam_id
     *
     * @return the value of score.exam_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.exam_id
     *
     * @param examId the value for score.exam_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.exam_name
     *
     * @return the value of score.exam_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.exam_name
     *
     * @param examName the value for score.exam_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.subject_id
     *
     * @return the value of score.subject_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.subject_id
     *
     * @param subjectId the value for score.subject_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.subject_name
     *
     * @return the value of score.subject_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.subject_name
     *
     * @param subjectName the value for score.subject_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.class_id
     *
     * @return the value of score.class_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.class_id
     *
     * @param classId the value for score.class_id
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.class_name
     *
     * @return the value of score.class_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.class_name
     *
     * @param className the value for score.class_name
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.submit_time
     *
     * @return the value of score.submit_time
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.submit_time
     *
     * @param submitTime the value for score.submit_time
     *
     * @mbggenerated Fri Apr 28 04:47:31 CST 2017
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
}