package com.internet.cms.model;

import java.util.Date;

public class Student extends PageInfo{
	private String birth;
	private String restudentPass;
    public String getRestudentPass() {
		return restudentPass;
	}

	public void setReStudentPass(String restudentPass) {
		this.restudentPass = restudentPass;
	}

	public String getBirth() {
		return birth;
	}

	public void setBirth(String birth) {
		this.birth = birth;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_no
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private String studentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_pass
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private String studentPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_sex
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private Integer studentSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_birth
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private Date studentBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_phone
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private String studentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_email
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private String studentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_state
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private Integer studentState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_name
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_no
     *
     * @return the value of student.student_no
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_no
     *
     * @param studentNo the value for student.student_no
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_pass
     *
     * @return the value of student.student_pass
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public String getStudentPass() {
        return studentPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_pass
     *
     * @param studentPass the value for student.student_pass
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentPass(String studentPass) {
        this.studentPass = studentPass == null ? null : studentPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_sex
     *
     * @return the value of student.student_sex
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public Integer getStudentSex() {
        return studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_sex
     *
     * @param studentSex the value for student.student_sex
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentSex(Integer studentSex) {
        this.studentSex = studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_birth
     *
     * @return the value of student.student_birth
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public Date getStudentBirth() {
        return studentBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_birth
     *
     * @param studentBirth the value for student.student_birth
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentBirth(Date studentBirth) {
        this.studentBirth = studentBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_phone
     *
     * @return the value of student.student_phone
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_phone
     *
     * @param studentPhone the value for student.student_phone
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone == null ? null : studentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_email
     *
     * @return the value of student.student_email
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public String getStudentEmail() {
        return studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_email
     *
     * @param studentEmail the value for student.student_email
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail == null ? null : studentEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_state
     *
     * @return the value of student.student_state
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public Integer getStudentState() {
        return studentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_state
     *
     * @param studentState the value for student.student_state
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setStudentState(Integer studentState) {
        this.studentState = studentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_name
     *
     * @return the value of student.class_name
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_name
     *
     * @param className the value for student.class_name
     *
     * @mbggenerated Wed Apr 19 13:15:07 CST 2017
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }
}