package com.internet.cms.model;

public class User extends PageInfo{

	private String reUserPass;
    
	public String getReUserPass() {
		return reUserPass;
	}

	public void setReUserPass(String reUserPass) {
		this.reUserPass = reUserPass;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pass
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private String userPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_sex
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_phone
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_state
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_detail
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private String userDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.subject_id
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.subject_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    private String subjectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_name
     *
     * @return the value of user.login_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_name
     *
     * @param loginName the value for user.login_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pass
     *
     * @return the value of user.user_pass
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pass
     *
     * @param userPass the value for user.user_pass
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass == null ? null : userPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_sex
     *
     * @return the value of user.user_sex
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_sex
     *
     * @param userSex the value for user.user_sex
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_phone
     *
     * @return the value of user.user_phone
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_phone
     *
     * @param userPhone the value for user.user_phone
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_state
     *
     * @return the value of user.user_state
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_state
     *
     * @param userState the value for user.user_state
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_detail
     *
     * @return the value of user.user_detail
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public String getUserDetail() {
        return userDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_detail
     *
     * @param userDetail the value for user.user_detail
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setUserDetail(String userDetail) {
        this.userDetail = userDetail == null ? null : userDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.subject_id
     *
     * @return the value of user.subject_id
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.subject_id
     *
     * @param subjectId the value for user.subject_id
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.subject_name
     *
     * @return the value of user.subject_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.subject_name
     *
     * @param subjectName the value for user.subject_name
     *
     * @mbggenerated Sat Apr 22 21:38:49 CST 2017
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }
}